//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ssofty_com_thuvienEntities : DbContext
    {
        public ssofty_com_thuvienEntities()
            : base("name=ssofty_com_thuvienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_BanQuyen> Tbl_BanQuyen { get; set; }
        public virtual DbSet<Tbl_BaoCao_SapXep> Tbl_BaoCao_SapXep { get; set; }
        public virtual DbSet<Tbl_BienMuc> Tbl_BienMuc { get; set; }
        public virtual DbSet<Tbl_DinhDangTaiLieu> Tbl_DinhDangTaiLieu { get; set; }
        public virtual DbSet<Tbl_DocGia> Tbl_DocGia { get; set; }
        public virtual DbSet<Tbl_KhoiHoc> Tbl_KhoiHoc { get; set; }
        public virtual DbSet<Tbl_KhoSach> Tbl_KhoSach { get; set; }
        public virtual DbSet<Tbl_KiemKe> Tbl_KiemKe { get; set; }
        public virtual DbSet<Tbl_KiemKeChiTiet> Tbl_KiemKeChiTiet { get; set; }
        public virtual DbSet<Tbl_KyHieuPhanLoai> Tbl_KyHieuPhanLoai { get; set; }
        public virtual DbSet<Tbl_LoaiVanBan> Tbl_LoaiVanBan { get; set; }
        public virtual DbSet<Tbl_LyDoPhatThe> Tbl_LyDoPhatThe { get; set; }
        public virtual DbSet<Tbl_MonHoc> Tbl_MonHoc { get; set; }
        public virtual DbSet<Tbl_NamHoc> Tbl_NamHoc { get; set; }
        public virtual DbSet<Tbl_NgonNgu> Tbl_NgonNgu { get; set; }
        public virtual DbSet<Tbl_NhaCungCap> Tbl_NhaCungCap { get; set; }
        public virtual DbSet<Tbl_NhaCungCap_TheoNgay> Tbl_NhaCungCap_TheoNgay { get; set; }
        public virtual DbSet<Tbl_NhaCungCap_TheoThang> Tbl_NhaCungCap_TheoThang { get; set; }
        public virtual DbSet<Tbl_NhaCungCap_TheoTuan> Tbl_NhaCungCap_TheoTuan { get; set; }
        public virtual DbSet<Tbl_NhanVien> Tbl_NhanVien { get; set; }
        public virtual DbSet<Tbl_NhapSach> Tbl_NhapSach { get; set; }
        public virtual DbSet<Tbl_NhaXuatBan> Tbl_NhaXuatBan { get; set; }
        public virtual DbSet<Tbl_NhomDocGia> Tbl_NhomDocGia { get; set; }
        public virtual DbSet<Tbl_NhomNguoiDung> Tbl_NhomNguoiDung { get; set; }
        public virtual DbSet<Tbl_PhanLoai> Tbl_PhanLoai { get; set; }
        public virtual DbSet<Tbl_PhanQuyen> Tbl_PhanQuyen { get; set; }
        public virtual DbSet<Tbl_PhatTheBanDoc> Tbl_PhatTheBanDoc { get; set; }
        public virtual DbSet<Tbl_PhongTruong> Tbl_PhongTruong { get; set; }
        public virtual DbSet<Tbl_Sach> Tbl_Sach { get; set; }
        public virtual DbSet<Tbl_SoCaBiet> Tbl_SoCaBiet { get; set; }
        public virtual DbSet<Tbl_SoTongQuat_Phan1> Tbl_SoTongQuat_Phan1 { get; set; }
        public virtual DbSet<Tbl_TacGia> Tbl_TacGia { get; set; }
        public virtual DbSet<Tbl_ThanhLy> Tbl_ThanhLy { get; set; }
        public virtual DbSet<Tbl_ThanhLyChiTiet> Tbl_ThanhLyChiTiet { get; set; }
        public virtual DbSet<Tbl_ThongTin> Tbl_ThongTin { get; set; }
        public virtual DbSet<Tbl_TinhChatNguonNhap> Tbl_TinhChatNguonNhap { get; set; }
        public virtual DbSet<Tbl_TinhTrangAnPham> Tbl_TinhTrangAnPham { get; set; }
        public virtual DbSet<Tbl_TongQuat_Phan1_1> Tbl_TongQuat_Phan1_1 { get; set; }
        public virtual DbSet<Tbl_TrangThaiAnPham> Tbl_TrangThaiAnPham { get; set; }
        public virtual DbSet<Tbl_VanBan> Tbl_VanBan { get; set; }
        public virtual DbSet<Tbl_XuatSachChiTiet> Tbl_XuatSachChiTiet { get; set; }
        public virtual DbSet<Tbl_XuatSachTong> Tbl_XuatSachTong { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UMS_GroupMenu> UMS_GroupMenu { get; set; }
        public virtual DbSet<UMS_Menu> UMS_Menu { get; set; }
        public virtual DbSet<UMS_MenuGroupUser> UMS_MenuGroupUser { get; set; }
        public virtual DbSet<UMS_UserGroups> UMS_UserGroups { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
    
        public virtual ObjectResult<BaoCaoChuaKiemKe_Result> BaoCaoChuaKiemKe(string maTruong)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaoCaoChuaKiemKe_Result>("BaoCaoChuaKiemKe", maTruongParameter);
        }
    
        public virtual ObjectResult<BCBanDocbyPhong_Result> BCBanDocbyPhong(string phong)
        {
            var phongParameter = phong != null ?
                new ObjectParameter("Phong", phong) :
                new ObjectParameter("Phong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BCBanDocbyPhong_Result>("BCBanDocbyPhong", phongParameter);
        }
    
        public virtual ObjectResult<BCSachbyPhong_Result> BCSachbyPhong(string phong)
        {
            var phongParameter = phong != null ?
                new ObjectParameter("Phong", phong) :
                new ObjectParameter("Phong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BCSachbyPhong_Result>("BCSachbyPhong", phongParameter);
        }
    
        public virtual ObjectResult<NhanAnPhamNgay_Result> NhanAnPhamNgay(string maTruong, string ngay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanAnPhamNgay_Result>("NhanAnPhamNgay", maTruongParameter, ngayParameter);
        }
    
        public virtual ObjectResult<NhanAnPhamThang_Result> NhanAnPhamThang(string maTruong, string ngay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanAnPhamThang_Result>("NhanAnPhamThang", maTruongParameter, ngayParameter);
        }
    
        public virtual ObjectResult<NhanAnPhamTuan_Result> NhanAnPhamTuan(string maTruong, string ngay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanAnPhamTuan_Result>("NhanAnPhamTuan", maTruongParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SoCaBiet_P1_01_Result> SoCaBiet_P1_01(string maTruong)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoCaBiet_P1_01_Result>("SoCaBiet_P1_01", maTruongParameter);
        }
    
        public virtual ObjectResult<SoTongQuat_P1_01_Result> SoTongQuat_P1_01(string maTruong)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoTongQuat_P1_01_Result>("SoTongQuat_P1_01", maTruongParameter);
        }
    
        public virtual int Tbl_BanQuyen_insert(string name, string lKey, string maTruong)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lKeyParameter = lKey != null ?
                new ObjectParameter("LKey", lKey) :
                new ObjectParameter("LKey", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_BanQuyen_insert", nameParameter, lKeyParameter, maTruongParameter);
        }
    
        public virtual int Tbl_DinhDangTaiLieu_insert(string ten, string ghiChu, Nullable<int> trangThai, string maTruong)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_DinhDangTaiLieu_insert", tenParameter, ghiChuParameter, trangThaiParameter, maTruongParameter);
        }
    
        public virtual int Tbl_DinhDangTaiLieu_update(string ten, string ghiChu, Nullable<int> trangThai, Nullable<int> ma, string maTruong)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_DinhDangTaiLieu_update", tenParameter, ghiChuParameter, trangThaiParameter, maParameter, maTruongParameter);
        }
    
        public virtual int Tbl_DocGia_insert(string maDocGia, string hoTen, string lop, Nullable<System.DateTime> ngayDangKy, Nullable<int> maNhom, string maTruong, string hinhAnh, string duongDan, string ftp)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var lopParameter = lop != null ?
                new ObjectParameter("Lop", lop) :
                new ObjectParameter("Lop", typeof(string));
    
            var ngayDangKyParameter = ngayDangKy.HasValue ?
                new ObjectParameter("NgayDangKy", ngayDangKy) :
                new ObjectParameter("NgayDangKy", typeof(System.DateTime));
    
            var maNhomParameter = maNhom.HasValue ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var duongDanParameter = duongDan != null ?
                new ObjectParameter("DuongDan", duongDan) :
                new ObjectParameter("DuongDan", typeof(string));
    
            var ftpParameter = ftp != null ?
                new ObjectParameter("Ftp", ftp) :
                new ObjectParameter("Ftp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_DocGia_insert", maDocGiaParameter, hoTenParameter, lopParameter, ngayDangKyParameter, maNhomParameter, maTruongParameter, hinhAnhParameter, duongDanParameter, ftpParameter);
        }
    
        public virtual int Tbl_DocGia_update(string maDocGia, string hoTen, string lop, Nullable<System.DateTime> ngayDangKy, Nullable<int> maNhom, string maTruong, string hinhAnh, string duongDan, string ftp)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var lopParameter = lop != null ?
                new ObjectParameter("Lop", lop) :
                new ObjectParameter("Lop", typeof(string));
    
            var ngayDangKyParameter = ngayDangKy.HasValue ?
                new ObjectParameter("NgayDangKy", ngayDangKy) :
                new ObjectParameter("NgayDangKy", typeof(System.DateTime));
    
            var maNhomParameter = maNhom.HasValue ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var duongDanParameter = duongDan != null ?
                new ObjectParameter("DuongDan", duongDan) :
                new ObjectParameter("DuongDan", typeof(string));
    
            var ftpParameter = ftp != null ?
                new ObjectParameter("Ftp", ftp) :
                new ObjectParameter("Ftp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_DocGia_update", maDocGiaParameter, hoTenParameter, lopParameter, ngayDangKyParameter, maNhomParameter, maTruongParameter, hinhAnhParameter, duongDanParameter, ftpParameter);
        }
    
        public virtual int Tbl_LoaiVanBan_insert(string tenLoai, string maTruong)
        {
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_LoaiVanBan_insert", tenLoaiParameter, maTruongParameter);
        }
    
        public virtual int Tbl_LoaiVanBan_update(string tenLoai, string maTruong, Nullable<int> maVanBan)
        {
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maVanBanParameter = maVanBan.HasValue ?
                new ObjectParameter("MaVanBan", maVanBan) :
                new ObjectParameter("MaVanBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_LoaiVanBan_update", tenLoaiParameter, maTruongParameter, maVanBanParameter);
        }
    
        public virtual int Tbl_LyDoPhatThe_insert(string ten, string ghiChu, Nullable<int> trangThai, string maTruong)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_LyDoPhatThe_insert", tenParameter, ghiChuParameter, trangThaiParameter, maTruongParameter);
        }
    
        public virtual int Tbl_LyDoPhatThe_update(string ten, string ghiChu, Nullable<int> trangThai, Nullable<int> ma, string maTruong)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_LyDoPhatThe_update", tenParameter, ghiChuParameter, trangThaiParameter, maParameter, maTruongParameter);
        }
    
        public virtual int Tbl_NgonNgu_insert(string kyHieu, string ten, string ghiChu, string maTruong)
        {
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NgonNgu_insert", kyHieuParameter, tenParameter, ghiChuParameter, maTruongParameter);
        }
    
        public virtual int Tbl_NgonNgu_update(string kyHieu, string ten, string ghiChu, Nullable<int> ma, string maTruong)
        {
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NgonNgu_update", kyHieuParameter, tenParameter, ghiChuParameter, maParameter, maTruongParameter);
        }
    
        public virtual int Tbl_NhaCungCap_insert(string ma, string maTruong, string ten, string diaChi, string sDT, string email, string mST, string nguoiLH, string noiDung, string thongBao, string kieuNhan, string trangThai, Nullable<System.DateTime> ngayTao)
        {
            var maParameter = ma != null ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mSTParameter = mST != null ?
                new ObjectParameter("MST", mST) :
                new ObjectParameter("MST", typeof(string));
    
            var nguoiLHParameter = nguoiLH != null ?
                new ObjectParameter("NguoiLH", nguoiLH) :
                new ObjectParameter("NguoiLH", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var thongBaoParameter = thongBao != null ?
                new ObjectParameter("ThongBao", thongBao) :
                new ObjectParameter("ThongBao", typeof(string));
    
            var kieuNhanParameter = kieuNhan != null ?
                new ObjectParameter("KieuNhan", kieuNhan) :
                new ObjectParameter("KieuNhan", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_insert", maParameter, maTruongParameter, tenParameter, diaChiParameter, sDTParameter, emailParameter, mSTParameter, nguoiLHParameter, noiDungParameter, thongBaoParameter, kieuNhanParameter, trangThaiParameter, ngayTaoParameter);
        }
    
        public virtual int Tbl_NhaCungCap_TheoNgay_insert(string maNCC, string maTruong, Nullable<System.DateTime> ngayBD, Nullable<int> soNgay, Nullable<int> cuoiTuan)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var soNgayParameter = soNgay.HasValue ?
                new ObjectParameter("SoNgay", soNgay) :
                new ObjectParameter("SoNgay", typeof(int));
    
            var cuoiTuanParameter = cuoiTuan.HasValue ?
                new ObjectParameter("CuoiTuan", cuoiTuan) :
                new ObjectParameter("CuoiTuan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_TheoNgay_insert", maNCCParameter, maTruongParameter, ngayBDParameter, soNgayParameter, cuoiTuanParameter);
        }
    
        public virtual int Tbl_NhaCungCap_TheoNgay_update(string maNCC, string maTruong, Nullable<System.DateTime> ngayBD, Nullable<int> soNgay, Nullable<int> cuoiTuan)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var soNgayParameter = soNgay.HasValue ?
                new ObjectParameter("SoNgay", soNgay) :
                new ObjectParameter("SoNgay", typeof(int));
    
            var cuoiTuanParameter = cuoiTuan.HasValue ?
                new ObjectParameter("CuoiTuan", cuoiTuan) :
                new ObjectParameter("CuoiTuan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_TheoNgay_update", maNCCParameter, maTruongParameter, ngayBDParameter, soNgayParameter, cuoiTuanParameter);
        }
    
        public virtual int Tbl_NhaCungCap_TheoThang_insert(string maNCC, string maTruong, Nullable<int> ngay)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_TheoThang_insert", maNCCParameter, maTruongParameter, ngayParameter);
        }
    
        public virtual int Tbl_NhaCungCap_TheoThang_update(string maNCC, string maTruong, Nullable<int> ngay)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_TheoThang_update", maNCCParameter, maTruongParameter, ngayParameter);
        }
    
        public virtual int Tbl_NhaCungCap_TheoTuan_insert(string maNCC, string maTruong, string thu)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var thuParameter = thu != null ?
                new ObjectParameter("Thu", thu) :
                new ObjectParameter("Thu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_TheoTuan_insert", maNCCParameter, maTruongParameter, thuParameter);
        }
    
        public virtual int Tbl_NhaCungCap_TheoTuan_update(string maNCC, string maTruong, string thu)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var thuParameter = thu != null ?
                new ObjectParameter("Thu", thu) :
                new ObjectParameter("Thu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_TheoTuan_update", maNCCParameter, maTruongParameter, thuParameter);
        }
    
        public virtual int Tbl_NhaCungCap_update(string ma, string maTruong, string ten, string diaChi, string sDT, string email, string mST, string nguoiLH, string noiDung, string thongBao, string kieuNhan, string trangThai, Nullable<System.DateTime> ngayTao)
        {
            var maParameter = ma != null ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mSTParameter = mST != null ?
                new ObjectParameter("MST", mST) :
                new ObjectParameter("MST", typeof(string));
    
            var nguoiLHParameter = nguoiLH != null ?
                new ObjectParameter("NguoiLH", nguoiLH) :
                new ObjectParameter("NguoiLH", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var thongBaoParameter = thongBao != null ?
                new ObjectParameter("ThongBao", thongBao) :
                new ObjectParameter("ThongBao", typeof(string));
    
            var kieuNhanParameter = kieuNhan != null ?
                new ObjectParameter("KieuNhan", kieuNhan) :
                new ObjectParameter("KieuNhan", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhaCungCap_update", maParameter, maTruongParameter, tenParameter, diaChiParameter, sDTParameter, emailParameter, mSTParameter, nguoiLHParameter, noiDungParameter, thongBaoParameter, kieuNhanParameter, trangThaiParameter, ngayTaoParameter);
        }
    
        public virtual int Tbl_NhanVien_insert(string maNV, string hoTen, string ngaySinh, string gioiTinh, string sDT, string diaChi, string email, string quyen, string matKhau, string maTruong, Nullable<bool> kichHoat)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh != null ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var quyenParameter = quyen != null ?
                new ObjectParameter("Quyen", quyen) :
                new ObjectParameter("Quyen", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var kichHoatParameter = kichHoat.HasValue ?
                new ObjectParameter("KichHoat", kichHoat) :
                new ObjectParameter("KichHoat", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhanVien_insert", maNVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, sDTParameter, diaChiParameter, emailParameter, quyenParameter, matKhauParameter, maTruongParameter, kichHoatParameter);
        }
    
        public virtual int Tbl_NhanVien_update(string maNV, string hoTen, string ngaySinh, string gioiTinh, string sDT, string diaChi, string email, string quyen, string matKhau, string maTruong, Nullable<bool> kichHoat)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh != null ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var quyenParameter = quyen != null ?
                new ObjectParameter("Quyen", quyen) :
                new ObjectParameter("Quyen", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var kichHoatParameter = kichHoat.HasValue ?
                new ObjectParameter("KichHoat", kichHoat) :
                new ObjectParameter("KichHoat", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhanVien_update", maNVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, sDTParameter, diaChiParameter, emailParameter, quyenParameter, matKhauParameter, maTruongParameter, kichHoatParameter);
        }
    
        public virtual int Tbl_NhapSach_insert(string maNhap, string maTruong, string maSach, Nullable<System.DateTime> ngayNhap, Nullable<int> soLuong, string daySach, string keSach, string tangSach, string nguoiNhap, string nhapCaBiet, string soCaBiet)
        {
            var maNhapParameter = maNhap != null ?
                new ObjectParameter("MaNhap", maNhap) :
                new ObjectParameter("MaNhap", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var daySachParameter = daySach != null ?
                new ObjectParameter("DaySach", daySach) :
                new ObjectParameter("DaySach", typeof(string));
    
            var keSachParameter = keSach != null ?
                new ObjectParameter("KeSach", keSach) :
                new ObjectParameter("KeSach", typeof(string));
    
            var tangSachParameter = tangSach != null ?
                new ObjectParameter("TangSach", tangSach) :
                new ObjectParameter("TangSach", typeof(string));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var nhapCaBietParameter = nhapCaBiet != null ?
                new ObjectParameter("NhapCaBiet", nhapCaBiet) :
                new ObjectParameter("NhapCaBiet", typeof(string));
    
            var soCaBietParameter = soCaBiet != null ?
                new ObjectParameter("SoCaBiet", soCaBiet) :
                new ObjectParameter("SoCaBiet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhapSach_insert", maNhapParameter, maTruongParameter, maSachParameter, ngayNhapParameter, soLuongParameter, daySachParameter, keSachParameter, tangSachParameter, nguoiNhapParameter, nhapCaBietParameter, soCaBietParameter);
        }
    
        public virtual int Tbl_NhapSach_update(string maNhap, string maTruong, string maSach, Nullable<System.DateTime> ngayNhap, Nullable<int> soLuong, string daySach, string keSach, string tangSach, string nguoiNhap, string nhapCaBiet, string soCaBiet)
        {
            var maNhapParameter = maNhap != null ?
                new ObjectParameter("MaNhap", maNhap) :
                new ObjectParameter("MaNhap", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var daySachParameter = daySach != null ?
                new ObjectParameter("DaySach", daySach) :
                new ObjectParameter("DaySach", typeof(string));
    
            var keSachParameter = keSach != null ?
                new ObjectParameter("KeSach", keSach) :
                new ObjectParameter("KeSach", typeof(string));
    
            var tangSachParameter = tangSach != null ?
                new ObjectParameter("TangSach", tangSach) :
                new ObjectParameter("TangSach", typeof(string));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var nhapCaBietParameter = nhapCaBiet != null ?
                new ObjectParameter("NhapCaBiet", nhapCaBiet) :
                new ObjectParameter("NhapCaBiet", typeof(string));
    
            var soCaBietParameter = soCaBiet != null ?
                new ObjectParameter("SoCaBiet", soCaBiet) :
                new ObjectParameter("SoCaBiet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhapSach_update", maNhapParameter, maTruongParameter, maSachParameter, ngayNhapParameter, soLuongParameter, daySachParameter, keSachParameter, tangSachParameter, nguoiNhapParameter, nhapCaBietParameter, soCaBietParameter);
        }
    
        public virtual int Tbl_NhomDocGia_insert(string tenNhom, Nullable<int> hanMuon, string maTruong, Nullable<int> soLuong)
        {
            var tenNhomParameter = tenNhom != null ?
                new ObjectParameter("TenNhom", tenNhom) :
                new ObjectParameter("TenNhom", typeof(string));
    
            var hanMuonParameter = hanMuon.HasValue ?
                new ObjectParameter("HanMuon", hanMuon) :
                new ObjectParameter("HanMuon", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhomDocGia_insert", tenNhomParameter, hanMuonParameter, maTruongParameter, soLuongParameter);
        }
    
        public virtual int Tbl_NhomDocGia_update(Nullable<int> maNhom, string tenNhom, Nullable<int> hanMuon, string maTruong, Nullable<int> soLuong)
        {
            var maNhomParameter = maNhom.HasValue ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(int));
    
            var tenNhomParameter = tenNhom != null ?
                new ObjectParameter("TenNhom", tenNhom) :
                new ObjectParameter("TenNhom", typeof(string));
    
            var hanMuonParameter = hanMuon.HasValue ?
                new ObjectParameter("HanMuon", hanMuon) :
                new ObjectParameter("HanMuon", typeof(int));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhomDocGia_update", maNhomParameter, tenNhomParameter, hanMuonParameter, maTruongParameter, soLuongParameter);
        }
    
        public virtual int Tbl_NhomNguoiDung_insert(string maNhom, string tenNhom, string maTruong)
        {
            var maNhomParameter = maNhom != null ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(string));
    
            var tenNhomParameter = tenNhom != null ?
                new ObjectParameter("TenNhom", tenNhom) :
                new ObjectParameter("TenNhom", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhomNguoiDung_insert", maNhomParameter, tenNhomParameter, maTruongParameter);
        }
    
        public virtual int Tbl_NhomNguoiDung_update(string maNhom, string tenNhom, string maTruong)
        {
            var maNhomParameter = maNhom != null ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(string));
    
            var tenNhomParameter = tenNhom != null ?
                new ObjectParameter("TenNhom", tenNhom) :
                new ObjectParameter("TenNhom", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_NhomNguoiDung_update", maNhomParameter, tenNhomParameter, maTruongParameter);
        }
    
        public virtual int Tbl_PhanLoai_insert(string maLoai, string tenLoai, string notes, string maTruong)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_PhanLoai_insert", maLoaiParameter, tenLoaiParameter, notesParameter, maTruongParameter);
        }
    
        public virtual int Tbl_PhanLoai_update(string maLoai, string tenLoai, string notes, string maTruong)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_PhanLoai_update", maLoaiParameter, tenLoaiParameter, notesParameter, maTruongParameter);
        }
    
        public virtual int Tbl_PhanQuyen_insert(string maNhom, string maChucNang, string chucNang, Nullable<int> thucThi, string loai, string maTruong)
        {
            var maNhomParameter = maNhom != null ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(string));
    
            var maChucNangParameter = maChucNang != null ?
                new ObjectParameter("MaChucNang", maChucNang) :
                new ObjectParameter("MaChucNang", typeof(string));
    
            var chucNangParameter = chucNang != null ?
                new ObjectParameter("ChucNang", chucNang) :
                new ObjectParameter("ChucNang", typeof(string));
    
            var thucThiParameter = thucThi.HasValue ?
                new ObjectParameter("ThucThi", thucThi) :
                new ObjectParameter("ThucThi", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_PhanQuyen_insert", maNhomParameter, maChucNangParameter, chucNangParameter, thucThiParameter, loaiParameter, maTruongParameter);
        }
    
        public virtual int Tbl_PhanQuyen_update(string maNhom, string maChucNang, string chucNang, Nullable<int> thucThi, string loai, string maTruong)
        {
            var maNhomParameter = maNhom != null ?
                new ObjectParameter("MaNhom", maNhom) :
                new ObjectParameter("MaNhom", typeof(string));
    
            var maChucNangParameter = maChucNang != null ?
                new ObjectParameter("MaChucNang", maChucNang) :
                new ObjectParameter("MaChucNang", typeof(string));
    
            var chucNangParameter = chucNang != null ?
                new ObjectParameter("ChucNang", chucNang) :
                new ObjectParameter("ChucNang", typeof(string));
    
            var thucThiParameter = thucThi.HasValue ?
                new ObjectParameter("ThucThi", thucThi) :
                new ObjectParameter("ThucThi", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_PhanQuyen_update", maNhomParameter, maChucNangParameter, chucNangParameter, thucThiParameter, loaiParameter, maTruongParameter);
        }
    
        public virtual int Tbl_PhongTruong_insert(string maPhong, string maTruong)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_PhongTruong_insert", maPhongParameter, maTruongParameter);
        }
    
        public virtual int Tbl_Sach_insert(string maSach, string tenSach, string noiDung, string tacGia, string nhaXuatBan, string ngayXuatBan, Nullable<double> giaTien, string maLoai, Nullable<int> soLuong, Nullable<System.DateTime> ngayNhap, string nguoiNhap, string ngonNgu, string maTruong, string anhBia, string duongDan, string ftp)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var tacGiaParameter = tacGia != null ?
                new ObjectParameter("TacGia", tacGia) :
                new ObjectParameter("TacGia", typeof(string));
    
            var nhaXuatBanParameter = nhaXuatBan != null ?
                new ObjectParameter("NhaXuatBan", nhaXuatBan) :
                new ObjectParameter("NhaXuatBan", typeof(string));
    
            var ngayXuatBanParameter = ngayXuatBan != null ?
                new ObjectParameter("NgayXuatBan", ngayXuatBan) :
                new ObjectParameter("NgayXuatBan", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(double));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var ngonNguParameter = ngonNgu != null ?
                new ObjectParameter("NgonNgu", ngonNgu) :
                new ObjectParameter("NgonNgu", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var anhBiaParameter = anhBia != null ?
                new ObjectParameter("AnhBia", anhBia) :
                new ObjectParameter("AnhBia", typeof(string));
    
            var duongDanParameter = duongDan != null ?
                new ObjectParameter("DuongDan", duongDan) :
                new ObjectParameter("DuongDan", typeof(string));
    
            var ftpParameter = ftp != null ?
                new ObjectParameter("Ftp", ftp) :
                new ObjectParameter("Ftp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_Sach_insert", maSachParameter, tenSachParameter, noiDungParameter, tacGiaParameter, nhaXuatBanParameter, ngayXuatBanParameter, giaTienParameter, maLoaiParameter, soLuongParameter, ngayNhapParameter, nguoiNhapParameter, ngonNguParameter, maTruongParameter, anhBiaParameter, duongDanParameter, ftpParameter);
        }
    
        public virtual int Tbl_Sach_update(string maSach, string tenSach, string noiDung, string tacGia, string nhaXuatBan, string ngayXuatBan, Nullable<double> giaTien, string maLoai, Nullable<int> soLuong, Nullable<System.DateTime> ngayNhap, string nguoiNhap, string ngonNgu, string maTruong, string anhBia, string duongDan, string ftp)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var tacGiaParameter = tacGia != null ?
                new ObjectParameter("TacGia", tacGia) :
                new ObjectParameter("TacGia", typeof(string));
    
            var nhaXuatBanParameter = nhaXuatBan != null ?
                new ObjectParameter("NhaXuatBan", nhaXuatBan) :
                new ObjectParameter("NhaXuatBan", typeof(string));
    
            var ngayXuatBanParameter = ngayXuatBan != null ?
                new ObjectParameter("NgayXuatBan", ngayXuatBan) :
                new ObjectParameter("NgayXuatBan", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(double));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var ngonNguParameter = ngonNgu != null ?
                new ObjectParameter("NgonNgu", ngonNgu) :
                new ObjectParameter("NgonNgu", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var anhBiaParameter = anhBia != null ?
                new ObjectParameter("AnhBia", anhBia) :
                new ObjectParameter("AnhBia", typeof(string));
    
            var duongDanParameter = duongDan != null ?
                new ObjectParameter("DuongDan", duongDan) :
                new ObjectParameter("DuongDan", typeof(string));
    
            var ftpParameter = ftp != null ?
                new ObjectParameter("Ftp", ftp) :
                new ObjectParameter("Ftp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_Sach_update", maSachParameter, tenSachParameter, noiDungParameter, tacGiaParameter, nhaXuatBanParameter, ngayXuatBanParameter, giaTienParameter, maLoaiParameter, soLuongParameter, ngayNhapParameter, nguoiNhapParameter, ngonNguParameter, maTruongParameter, anhBiaParameter, duongDanParameter, ftpParameter);
        }
    
        public virtual int Tbl_SoCaBiet_insert(string sTT, string maTruong, string maNhap, string maSach, Nullable<System.DateTime> ngayNhap, string trangThai)
        {
            var sTTParameter = sTT != null ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maNhapParameter = maNhap != null ?
                new ObjectParameter("MaNhap", maNhap) :
                new ObjectParameter("MaNhap", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_SoCaBiet_insert", sTTParameter, maTruongParameter, maNhapParameter, maSachParameter, ngayNhapParameter, trangThaiParameter);
        }
    
        public virtual int Tbl_SoCaBiet_update(string sTT, string maTruong, string maNhap, string maSach, Nullable<System.DateTime> ngayNhap, string trangThai)
        {
            var sTTParameter = sTT != null ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maNhapParameter = maNhap != null ?
                new ObjectParameter("MaNhap", maNhap) :
                new ObjectParameter("MaNhap", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_SoCaBiet_update", sTTParameter, maTruongParameter, maNhapParameter, maSachParameter, ngayNhapParameter, trangThaiParameter);
        }
    
        public virtual int Tbl_TacGia_insert(string tenTacGia, string maTruong)
        {
            var tenTacGiaParameter = tenTacGia != null ?
                new ObjectParameter("TenTacGia", tenTacGia) :
                new ObjectParameter("TenTacGia", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_TacGia_insert", tenTacGiaParameter, maTruongParameter);
        }
    
        public virtual int Tbl_TacGia_update(Nullable<int> maTG, string tenTacGia, string maTruong)
        {
            var maTGParameter = maTG.HasValue ?
                new ObjectParameter("MaTG", maTG) :
                new ObjectParameter("MaTG", typeof(int));
    
            var tenTacGiaParameter = tenTacGia != null ?
                new ObjectParameter("TenTacGia", tenTacGia) :
                new ObjectParameter("TenTacGia", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_TacGia_update", maTGParameter, tenTacGiaParameter, maTruongParameter);
        }
    
        public virtual int Tbl_ThanhLy_insert(string maTL, string maTruong, Nullable<System.DateTime> ngayTL, string nguoiNhap, Nullable<int> soLuong)
        {
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayTLParameter = ngayTL.HasValue ?
                new ObjectParameter("NgayTL", ngayTL) :
                new ObjectParameter("NgayTL", typeof(System.DateTime));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_ThanhLy_insert", maTLParameter, maTruongParameter, ngayTLParameter, nguoiNhapParameter, soLuongParameter);
        }
    
        public virtual int Tbl_ThanhLy_update(string maTL, string maTruong, Nullable<System.DateTime> ngayTL, string nguoiNhap, Nullable<int> soLuong)
        {
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayTLParameter = ngayTL.HasValue ?
                new ObjectParameter("NgayTL", ngayTL) :
                new ObjectParameter("NgayTL", typeof(System.DateTime));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_ThanhLy_update", maTLParameter, maTruongParameter, ngayTLParameter, nguoiNhapParameter, soLuongParameter);
        }
    
        public virtual int Tbl_ThanhLyChiTiet_insert(string maTL, string maTruong, string soCaBiet, string maSach, Nullable<System.DateTime> ngayTao)
        {
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var soCaBietParameter = soCaBiet != null ?
                new ObjectParameter("SoCaBiet", soCaBiet) :
                new ObjectParameter("SoCaBiet", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_ThanhLyChiTiet_insert", maTLParameter, maTruongParameter, soCaBietParameter, maSachParameter, ngayTaoParameter);
        }
    
        public virtual int Tbl_ThanhLyChiTiet_update(string maTL, string maTruong, string soCaBiet, string maSach, Nullable<System.DateTime> ngayTao)
        {
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var soCaBietParameter = soCaBiet != null ?
                new ObjectParameter("SoCaBiet", soCaBiet) :
                new ObjectParameter("SoCaBiet", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_ThanhLyChiTiet_update", maTLParameter, maTruongParameter, soCaBietParameter, maSachParameter, ngayTaoParameter);
        }
    
        public virtual ObjectResult<Tbl_Thongketheokhosach_Result> Tbl_Thongketheokhosach(string maTruong, string tuNgay, string denNgay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Thongketheokhosach_Result>("Tbl_Thongketheokhosach", maTruongParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Tbl_Thongketheomonloai_Result> Tbl_Thongketheomonloai(string maTruong, string tuNgay, string denNgay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Thongketheomonloai_Result>("Tbl_Thongketheomonloai", maTruongParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Tbl_Thongketheonamxuatban_Result> Tbl_Thongketheonamxuatban(string maTruong, string tuNgay, string denNgay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Thongketheonamxuatban_Result>("Tbl_Thongketheonamxuatban", maTruongParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Tbl_Thongketheonhande_Result> Tbl_Thongketheonhande(string maTruong, string tuNgay, string denNgay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Thongketheonhande_Result>("Tbl_Thongketheonhande", maTruongParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int Tbl_ThongTin_insert(string maTruong, string tenTruong, string diaChi, string soDienThoai, string fax, string email, string website, string hieuTruong, string namHoc, Nullable<bool> phong, string maSach)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tenTruongParameter = tenTruong != null ?
                new ObjectParameter("TenTruong", tenTruong) :
                new ObjectParameter("TenTruong", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("Website", website) :
                new ObjectParameter("Website", typeof(string));
    
            var hieuTruongParameter = hieuTruong != null ?
                new ObjectParameter("HieuTruong", hieuTruong) :
                new ObjectParameter("HieuTruong", typeof(string));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("NamHoc", namHoc) :
                new ObjectParameter("NamHoc", typeof(string));
    
            var phongParameter = phong.HasValue ?
                new ObjectParameter("Phong", phong) :
                new ObjectParameter("Phong", typeof(bool));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_ThongTin_insert", maTruongParameter, tenTruongParameter, diaChiParameter, soDienThoaiParameter, faxParameter, emailParameter, websiteParameter, hieuTruongParameter, namHocParameter, phongParameter, maSachParameter);
        }
    
        public virtual int Tbl_ThongTin_update(string maTruong, string tenTruong, string diaChi, string soDienThoai, string fax, string email, string website, string hieuTruong, string namHoc, Nullable<bool> phong, string maSach)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tenTruongParameter = tenTruong != null ?
                new ObjectParameter("TenTruong", tenTruong) :
                new ObjectParameter("TenTruong", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("Website", website) :
                new ObjectParameter("Website", typeof(string));
    
            var hieuTruongParameter = hieuTruong != null ?
                new ObjectParameter("HieuTruong", hieuTruong) :
                new ObjectParameter("HieuTruong", typeof(string));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("NamHoc", namHoc) :
                new ObjectParameter("NamHoc", typeof(string));
    
            var phongParameter = phong.HasValue ?
                new ObjectParameter("Phong", phong) :
                new ObjectParameter("Phong", typeof(bool));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_ThongTin_update", maTruongParameter, tenTruongParameter, diaChiParameter, soDienThoaiParameter, faxParameter, emailParameter, websiteParameter, hieuTruongParameter, namHocParameter, phongParameter, maSachParameter);
        }
    
        public virtual int Tbl_VanBan_insert(string maVB, string maTruong, string tenVB, string tieuDe, string noiGui, Nullable<System.DateTime> ngayNhan, Nullable<int> loaiVB, Nullable<System.DateTime> ngayNhap, string nguoiNhap, string duongDan, string tenFile)
        {
            var maVBParameter = maVB != null ?
                new ObjectParameter("MaVB", maVB) :
                new ObjectParameter("MaVB", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tenVBParameter = tenVB != null ?
                new ObjectParameter("TenVB", tenVB) :
                new ObjectParameter("TenVB", typeof(string));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiGuiParameter = noiGui != null ?
                new ObjectParameter("NoiGui", noiGui) :
                new ObjectParameter("NoiGui", typeof(string));
    
            var ngayNhanParameter = ngayNhan.HasValue ?
                new ObjectParameter("NgayNhan", ngayNhan) :
                new ObjectParameter("NgayNhan", typeof(System.DateTime));
    
            var loaiVBParameter = loaiVB.HasValue ?
                new ObjectParameter("LoaiVB", loaiVB) :
                new ObjectParameter("LoaiVB", typeof(int));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var duongDanParameter = duongDan != null ?
                new ObjectParameter("DuongDan", duongDan) :
                new ObjectParameter("DuongDan", typeof(string));
    
            var tenFileParameter = tenFile != null ?
                new ObjectParameter("TenFile", tenFile) :
                new ObjectParameter("TenFile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_VanBan_insert", maVBParameter, maTruongParameter, tenVBParameter, tieuDeParameter, noiGuiParameter, ngayNhanParameter, loaiVBParameter, ngayNhapParameter, nguoiNhapParameter, duongDanParameter, tenFileParameter);
        }
    
        public virtual int Tbl_VanBan_update(string maVB, string maTruong, string tenVB, string tieuDe, string noiGui, Nullable<System.DateTime> ngayNhan, Nullable<int> loaiVB, Nullable<System.DateTime> ngayNhap, string nguoiNhap, string duongDan, string tenFile)
        {
            var maVBParameter = maVB != null ?
                new ObjectParameter("MaVB", maVB) :
                new ObjectParameter("MaVB", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tenVBParameter = tenVB != null ?
                new ObjectParameter("TenVB", tenVB) :
                new ObjectParameter("TenVB", typeof(string));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiGuiParameter = noiGui != null ?
                new ObjectParameter("NoiGui", noiGui) :
                new ObjectParameter("NoiGui", typeof(string));
    
            var ngayNhanParameter = ngayNhan.HasValue ?
                new ObjectParameter("NgayNhan", ngayNhan) :
                new ObjectParameter("NgayNhan", typeof(System.DateTime));
    
            var loaiVBParameter = loaiVB.HasValue ?
                new ObjectParameter("LoaiVB", loaiVB) :
                new ObjectParameter("LoaiVB", typeof(int));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var duongDanParameter = duongDan != null ?
                new ObjectParameter("DuongDan", duongDan) :
                new ObjectParameter("DuongDan", typeof(string));
    
            var tenFileParameter = tenFile != null ?
                new ObjectParameter("TenFile", tenFile) :
                new ObjectParameter("TenFile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_VanBan_update", maVBParameter, maTruongParameter, tenVBParameter, tieuDeParameter, noiGuiParameter, ngayNhanParameter, loaiVBParameter, ngayNhapParameter, nguoiNhapParameter, duongDanParameter, tenFileParameter);
        }
    
        public virtual int Tbl_XuatSachChiTiet_insert(string maXuat, string maTruong, string maSach, string soCaBiet, Nullable<int> soLuong, Nullable<bool> daTra, Nullable<System.DateTime> ngayXuat, string ghiChu, string trangThai, Nullable<System.DateTime> ngayTra)
        {
            var maXuatParameter = maXuat != null ?
                new ObjectParameter("MaXuat", maXuat) :
                new ObjectParameter("MaXuat", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soCaBietParameter = soCaBiet != null ?
                new ObjectParameter("SoCaBiet", soCaBiet) :
                new ObjectParameter("SoCaBiet", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var daTraParameter = daTra.HasValue ?
                new ObjectParameter("DaTra", daTra) :
                new ObjectParameter("DaTra", typeof(bool));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("NgayXuat", ngayXuat) :
                new ObjectParameter("NgayXuat", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_XuatSachChiTiet_insert", maXuatParameter, maTruongParameter, maSachParameter, soCaBietParameter, soLuongParameter, daTraParameter, ngayXuatParameter, ghiChuParameter, trangThaiParameter, ngayTraParameter);
        }
    
        public virtual int Tbl_XuatSachChiTiet_update(string maXuat, string maTruong, string maSach, string soCaBiet, Nullable<int> soLuong, Nullable<bool> daTra, Nullable<System.DateTime> ngayXuat, string ghiChu, string trangThai, Nullable<System.DateTime> ngayTra)
        {
            var maXuatParameter = maXuat != null ?
                new ObjectParameter("MaXuat", maXuat) :
                new ObjectParameter("MaXuat", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soCaBietParameter = soCaBiet != null ?
                new ObjectParameter("SoCaBiet", soCaBiet) :
                new ObjectParameter("SoCaBiet", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var daTraParameter = daTra.HasValue ?
                new ObjectParameter("DaTra", daTra) :
                new ObjectParameter("DaTra", typeof(bool));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("NgayXuat", ngayXuat) :
                new ObjectParameter("NgayXuat", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_XuatSachChiTiet_update", maXuatParameter, maTruongParameter, maSachParameter, soCaBietParameter, soLuongParameter, daTraParameter, ngayXuatParameter, ghiChuParameter, trangThaiParameter, ngayTraParameter);
        }
    
        public virtual int Tbl_XuatSachTong_insert(string maXuat, string maHS, Nullable<int> soLuong, Nullable<System.DateTime> ngayMuon, Nullable<System.DateTime> ngayTra, string ghiChu, Nullable<System.DateTime> ngayXuat, string daTra, string trangThai, string nguoiNhap, string maTruong, Nullable<System.DateTime> ngayCapNhat)
        {
            var maXuatParameter = maXuat != null ?
                new ObjectParameter("MaXuat", maXuat) :
                new ObjectParameter("MaXuat", typeof(string));
    
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ngayMuonParameter = ngayMuon.HasValue ?
                new ObjectParameter("NgayMuon", ngayMuon) :
                new ObjectParameter("NgayMuon", typeof(System.DateTime));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("NgayXuat", ngayXuat) :
                new ObjectParameter("NgayXuat", typeof(System.DateTime));
    
            var daTraParameter = daTra != null ?
                new ObjectParameter("DaTra", daTra) :
                new ObjectParameter("DaTra", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayCapNhatParameter = ngayCapNhat.HasValue ?
                new ObjectParameter("NgayCapNhat", ngayCapNhat) :
                new ObjectParameter("NgayCapNhat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_XuatSachTong_insert", maXuatParameter, maHSParameter, soLuongParameter, ngayMuonParameter, ngayTraParameter, ghiChuParameter, ngayXuatParameter, daTraParameter, trangThaiParameter, nguoiNhapParameter, maTruongParameter, ngayCapNhatParameter);
        }
    
        public virtual int Tbl_XuatSachTong_update(string maXuat, string maHS, Nullable<int> soLuong, Nullable<System.DateTime> ngayMuon, Nullable<System.DateTime> ngayTra, string ghiChu, Nullable<System.DateTime> ngayXuat, string daTra, string trangThai, string nguoiNhap, string maTruong, Nullable<System.DateTime> ngayCapNhat)
        {
            var maXuatParameter = maXuat != null ?
                new ObjectParameter("MaXuat", maXuat) :
                new ObjectParameter("MaXuat", typeof(string));
    
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ngayMuonParameter = ngayMuon.HasValue ?
                new ObjectParameter("NgayMuon", ngayMuon) :
                new ObjectParameter("NgayMuon", typeof(System.DateTime));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("NgayXuat", ngayXuat) :
                new ObjectParameter("NgayXuat", typeof(System.DateTime));
    
            var daTraParameter = daTra != null ?
                new ObjectParameter("DaTra", daTra) :
                new ObjectParameter("DaTra", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var nguoiNhapParameter = nguoiNhap != null ?
                new ObjectParameter("NguoiNhap", nguoiNhap) :
                new ObjectParameter("NguoiNhap", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var ngayCapNhatParameter = ngayCapNhat.HasValue ?
                new ObjectParameter("NgayCapNhat", ngayCapNhat) :
                new ObjectParameter("NgayCapNhat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tbl_XuatSachTong_update", maXuatParameter, maHSParameter, soLuongParameter, ngayMuonParameter, ngayTraParameter, ghiChuParameter, ngayXuatParameter, daTraParameter, trangThaiParameter, nguoiNhapParameter, maTruongParameter, ngayCapNhatParameter);
        }
    
        public virtual ObjectResult<ThongKe_AnPham_MuonNhieuNhat_Result> ThongKe_AnPham_MuonNhieuNhat(string maTruong, string tuNgay, string denNgay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKe_AnPham_MuonNhieuNhat_Result>("ThongKe_AnPham_MuonNhieuNhat", maTruongParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<ThongKe_BanDoc_MuonNhieuNhat_Result> ThongKe_BanDoc_MuonNhieuNhat(string maTruong, string tuNgay, string denNgay)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKe_BanDoc_MuonNhieuNhat_Result>("ThongKe_BanDoc_MuonNhieuNhat", maTruongParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int UpdateSoCaBietKho_MuonSach(string maTruong, string maXuat)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maXuatParameter = maXuat != null ?
                new ObjectParameter("MaXuat", maXuat) :
                new ObjectParameter("MaXuat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSoCaBietKho_MuonSach", maTruongParameter, maXuatParameter);
        }
    
        public virtual ObjectResult<GROUPUSER_GETLISTMENU_Result> GROUPUSER_GETLISTMENU(string groupId)
        {
            var groupIdParameter = groupId != null ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GROUPUSER_GETLISTMENU_Result>("GROUPUSER_GETLISTMENU", groupIdParameter);
        }
    
        public virtual ObjectResult<USER_CHECKACCESS_Result> USER_CHECKACCESS(string groupId, string menuCode)
        {
            var groupIdParameter = groupId != null ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(string));
    
            var menuCodeParameter = menuCode != null ?
                new ObjectParameter("menuCode", menuCode) :
                new ObjectParameter("menuCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_CHECKACCESS_Result>("USER_CHECKACCESS", groupIdParameter, menuCodeParameter);
        }
    
        public virtual ObjectResult<USER_CHECKADMIN_Result> USER_CHECKADMIN(string user, string role)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_CHECKADMIN_Result>("USER_CHECKADMIN", userParameter, roleParameter);
        }
    
        public virtual ObjectResult<USER_GETMENU_Result> USER_GETMENU(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_GETMENU_Result>("USER_GETMENU", userParameter);
        }
    }
}
