//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ssofty_com_thuvienEntities : DbContext
    {
        public ssofty_com_thuvienEntities()
            : base("name=ssofty_com_thuvienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Tbl_BanQuyen> Tbl_BanQuyen { get; set; }
        public virtual DbSet<Tbl_BaoCao_SapXep> Tbl_BaoCao_SapXep { get; set; }
        public virtual DbSet<Tbl_BienMuc> Tbl_BienMuc { get; set; }
        public virtual DbSet<Tbl_DinhDangTaiLieu> Tbl_DinhDangTaiLieu { get; set; }
        public virtual DbSet<Tbl_DocGia> Tbl_DocGia { get; set; }
        public virtual DbSet<Tbl_KhoiHoc> Tbl_KhoiHoc { get; set; }
        public virtual DbSet<Tbl_KhoSach> Tbl_KhoSach { get; set; }
        public virtual DbSet<Tbl_KiemKe> Tbl_KiemKe { get; set; }
        public virtual DbSet<Tbl_KiemKeChiTiet> Tbl_KiemKeChiTiet { get; set; }
        public virtual DbSet<Tbl_KyHieuPhanLoai> Tbl_KyHieuPhanLoai { get; set; }
        public virtual DbSet<Tbl_LoaiVanBan> Tbl_LoaiVanBan { get; set; }
        public virtual DbSet<Tbl_LyDoPhatThe> Tbl_LyDoPhatThe { get; set; }
        public virtual DbSet<Tbl_MonHoc> Tbl_MonHoc { get; set; }
        public virtual DbSet<Tbl_NamHoc> Tbl_NamHoc { get; set; }
        public virtual DbSet<Tbl_NgonNgu> Tbl_NgonNgu { get; set; }
        public virtual DbSet<Tbl_NhaCungCap> Tbl_NhaCungCap { get; set; }
        public virtual DbSet<Tbl_NhaCungCap_TheoNgay> Tbl_NhaCungCap_TheoNgay { get; set; }
        public virtual DbSet<Tbl_NhaCungCap_TheoThang> Tbl_NhaCungCap_TheoThang { get; set; }
        public virtual DbSet<Tbl_NhaCungCap_TheoTuan> Tbl_NhaCungCap_TheoTuan { get; set; }
        public virtual DbSet<Tbl_NhanVien> Tbl_NhanVien { get; set; }
        public virtual DbSet<Tbl_NhapSach> Tbl_NhapSach { get; set; }
        public virtual DbSet<Tbl_NhaXuatBan> Tbl_NhaXuatBan { get; set; }
        public virtual DbSet<Tbl_NhomDocGia> Tbl_NhomDocGia { get; set; }
        public virtual DbSet<Tbl_NhomNguoiDung> Tbl_NhomNguoiDung { get; set; }
        public virtual DbSet<Tbl_PhanLoai> Tbl_PhanLoai { get; set; }
        public virtual DbSet<Tbl_PhanQuyen> Tbl_PhanQuyen { get; set; }
        public virtual DbSet<Tbl_PhatTheBanDoc> Tbl_PhatTheBanDoc { get; set; }
        public virtual DbSet<Tbl_PhongTruong> Tbl_PhongTruong { get; set; }
        public virtual DbSet<Tbl_Sach> Tbl_Sach { get; set; }
        public virtual DbSet<Tbl_SoCaBiet> Tbl_SoCaBiet { get; set; }
        public virtual DbSet<Tbl_SoTongQuat_Phan1> Tbl_SoTongQuat_Phan1 { get; set; }
        public virtual DbSet<Tbl_TacGia> Tbl_TacGia { get; set; }
        public virtual DbSet<Tbl_ThanhLy> Tbl_ThanhLy { get; set; }
        public virtual DbSet<Tbl_ThanhLyChiTiet> Tbl_ThanhLyChiTiet { get; set; }
        public virtual DbSet<Tbl_ThongTin> Tbl_ThongTin { get; set; }
        public virtual DbSet<Tbl_TinhChatNguonNhap> Tbl_TinhChatNguonNhap { get; set; }
        public virtual DbSet<Tbl_TinhTrangAnPham> Tbl_TinhTrangAnPham { get; set; }
        public virtual DbSet<Tbl_TongQuat_Phan1_1> Tbl_TongQuat_Phan1_1 { get; set; }
        public virtual DbSet<Tbl_TrangThaiAnPham> Tbl_TrangThaiAnPham { get; set; }
        public virtual DbSet<Tbl_VanBan> Tbl_VanBan { get; set; }
        public virtual DbSet<Tbl_XuatSachChiTiet> Tbl_XuatSachChiTiet { get; set; }
        public virtual DbSet<Tbl_XuatSachTong> Tbl_XuatSachTong { get; set; }
        public virtual DbSet<UMS_GroupMenu> UMS_GroupMenu { get; set; }
        public virtual DbSet<UMS_Menu> UMS_Menu { get; set; }
        public virtual DbSet<UMS_MenuGroupUser> UMS_MenuGroupUser { get; set; }
        public virtual DbSet<UMS_UserGroups> UMS_UserGroups { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
    
        public virtual ObjectResult<GROUPUSER_GETLISTMENU_Result> GROUPUSER_GETLISTMENU(string groupId)
        {
            var groupIdParameter = groupId != null ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GROUPUSER_GETLISTMENU_Result>("GROUPUSER_GETLISTMENU", groupIdParameter);
        }
    
        public virtual ObjectResult<USER_CHECKACCESS_Result> USER_CHECKACCESS(string groupId, string menuCode)
        {
            var groupIdParameter = groupId != null ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(string));
    
            var menuCodeParameter = menuCode != null ?
                new ObjectParameter("menuCode", menuCode) :
                new ObjectParameter("menuCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_CHECKACCESS_Result>("USER_CHECKACCESS", groupIdParameter, menuCodeParameter);
        }
    
        public virtual ObjectResult<USER_CHECKADMIN_Result> USER_CHECKADMIN(string user, string role)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_CHECKADMIN_Result>("USER_CHECKADMIN", userParameter, roleParameter);
        }
    
        public virtual ObjectResult<USER_GETMENU_Result> USER_GETMENU(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_GETMENU_Result>("USER_GETMENU", userParameter);
        }
    
        public virtual ObjectResult<Rpt_TheThuVien_Result> Rpt_TheThuVien(string maTruong)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_TheThuVien_Result>("Rpt_TheThuVien", maTruongParameter);
        }
    
        public virtual ObjectResult<Rpt_PhatTheBanDoc_Result> Rpt_PhatTheBanDoc(string maTruong, Nullable<int> ma)
        {
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_PhatTheBanDoc_Result>("Rpt_PhatTheBanDoc", maTruongParameter, maParameter);
        }
    }
}
