//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NhapSach
    {
        public string MaNhap { get; set; }
        public string MaTruong { get; set; }
        public string MaSach { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DaySach { get; set; }
        public string KeSach { get; set; }
        public string TangSach { get; set; }
        public string NguoiNhap { get; set; }
        public string NhapCaBiet { get; set; }
        public string SoCaBiet { get; set; }
    }
}
