//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PhatTheBanDoc
    {
        public string MaTruong { get; set; }
        public int Ma { get; set; }
        public string SoThe { get; set; }
        public Nullable<System.DateTime> NgayPhat { get; set; }
        public Nullable<int> LyDo { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string Khac { get; set; }
        public string GhiChu { get; set; }
    }
}
