//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NhaCungCap_TheoNgay
    {
        public string MaNCC { get; set; }
        public string MaTruong { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> CuoiTuan { get; set; }
    }
}
