//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KiemKe
    {
        public string MaTruong { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public string NguoiNhap { get; set; }
    }
}
