//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KiemKeChiTiet
    {
        public string Ma { get; set; }
        public string MaTruong { get; set; }
        public string SoCaBiet { get; set; }
        public string MaSach { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
