//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PhanQuyen
    {
        public string MaNhom { get; set; }
        public string MaChucNang { get; set; }
        public string ChucNang { get; set; }
        public Nullable<int> ThucThi { get; set; }
        public string Loai { get; set; }
        public string MaTruong { get; set; }
    }
}
