//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ThongTin
    {
        public string MaTruong { get; set; }
        public string TenTruong { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string HieuTruong { get; set; }
        public Nullable<int> NamHoc { get; set; }
        public Nullable<bool> Phong { get; set; }
        public string MaSach { get; set; }
        public string DonViCapTren { get; set; }
        public string KeToan { get; set; }
        public string ThuThu { get; set; }
    }
}
