//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sach
    {
        public string MaTruong { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> KhoiHoc { get; set; }
        public Nullable<int> MonHoc { get; set; }
        public string MaLoai { get; set; }
        public string KyHieuPhanLoai { get; set; }
        public Nullable<int> NgonNgu { get; set; }
        public string NhanDe { get; set; }
        public string NhanDeSongSong { get; set; }
        public string PhuDe { get; set; }
        public Nullable<int> TacGia { get; set; }
        public string DongTacGia { get; set; }
        public string NguoiDich { get; set; }
        public string NoiDung { get; set; }
        public string ThongTinTrachNhiem { get; set; }
        public string TuKhoa { get; set; }
        public string ChuDeChuyenMuc { get; set; }
        public string ThongTinTap { get; set; }
        public string TungThu { get; set; }
        public Nullable<int> NhaXuatBan { get; set; }
        public string LanXuatBan { get; set; }
        public string NoiXuatBan { get; set; }
        public string NamXuatBan { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string KichCo { get; set; }
        public string TaiLieuKemTheo { get; set; }
        public Nullable<int> DangLuuTru { get; set; }
        public string PhuChuAnPham { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<double> GiaBia { get; set; }
    }
}
