//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BienMuc
    {
        public string MaTruong { get; set; }
        public int Ma { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayVaoSo { get; set; }
        public string NhanTu { get; set; }
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayChungTu { get; set; }
        public Nullable<int> Nguon { get; set; }
        public string KhoNhap { get; set; }
        public string NhanDe { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<bool> BienMuc { get; set; }
        public Nullable<bool> CaBiet { get; set; }
        public string DayCaBiet { get; set; }
        public string MaSach { get; set; }
    }
}
