//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DocGia
    {
        public string MaTruong { get; set; }
        public string MaDocGia { get; set; }
        public string HoTen { get; set; }
        public string Lop { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string SoThe { get; set; }
        public string TrangThai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    }
}
