//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_XuatSachTong
    {
        public string MaXuat { get; set; }
        public string MaHS { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string DaTra { get; set; }
        public string TrangThai { get; set; }
        public string NguoiNhap { get; set; }
        public string MaTruong { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string HinhThuc { get; set; }
    }
}
