//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TongQuat_Phan1_1
    {
        public Nullable<double> TongSo_TriGia { get; set; }
        public Nullable<int> PhanLoai_NoiDung_GiaoKhoa { get; set; }
        public Nullable<int> PhanLoai_NoiDung_ThamKhao { get; set; }
        public Nullable<int> PhanLoai_NoiDung_NghiepVu { get; set; }
        public Nullable<int> PhanLoa_NoiDungi_ThieuNhi { get; set; }
        public Nullable<int> PhanLoai_NoiDung_Khac { get; set; }
        public Nullable<int> PhanLoai_NgonNgu_Anh { get; set; }
        public Nullable<int> PhanLoai_NgonNgu_Phap { get; set; }
        public Nullable<int> PhanLoai_NgonNgu_Khac { get; set; }
        public string PhuChu { get; set; }
        public string MaTruong { get; set; }
    }
}
