//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_VanBan
    {
        public string MaVB { get; set; }
        public string MaTruong { get; set; }
        public string TenVB { get; set; }
        public string TieuDe { get; set; }
        public string NoiGui { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<int> LoaiVB { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiNhap { get; set; }
        public string DuongDan { get; set; }
        public string TenFile { get; set; }
    }
}
